Cypress.Commands.add('deleteAllUsers', () => {
    cy.exec('python delete.py', { failOnNonZeroExit: true })
});

describe('test anotações', () => {
    
    it('cenario1', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signup/"]').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('#email').type("A@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(5) > a').click()
        cy.wait(1500)
        cy.get('#titulo').type("Anotação do dia")
        cy.wait(1500)
        cy.get('#anotacao').type("Lembrar de terminar o projeto")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get('.card-body > .btn-primary').click()
        cy.wait(1500)
        cy.get('.modal-footer > .btn').click()
        cy.wait(1500)
    })
    it('cenario2', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signup/"]').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('#email').type("A@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(5) > a').click()
        cy.wait(1500)
        cy.get('#titulo').type("Anotação do trabalho")
        cy.wait(1500)
        cy.get('#anotacao').type("Falta resolver os problemas")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get('.card-body > .btn-primary').click()
        cy.wait(1500)
        cy.get('.modal-footer > .btn').click()
        cy.wait(1500)
        cy.get('.btn-warning').click()
        cy.wait(1500)
        cy.get('#anotacao').type("Terminar de ajudar meu colega no trabalho x")
        cy.wait(1500)
        cy.get('.btn-primary').click()
        cy.wait(1500)
        cy.get('.card-body > .btn-primary').click()
        cy.wait(1500)
        cy.get('.modal-footer > .btn').click()
        cy.wait(1500)
    })
    it('cenario3', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signup/"]').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('#email').type("A@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("Arthur")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(5) > a').click()
        cy.wait(1500)
        cy.get('#titulo').type("Anotação da semana")
        cy.wait(1500)
        cy.get('#anotacao').type("Os trabalhos diurnos e noturnos precisam ser finalizados")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get('.btn-danger').click()
        cy.wait(1500)
    })

})