Cypress.Commands.add('deleteAllUsers', () => {
    cy.exec('python delete.py', { failOnNonZeroExit: true })
});

describe('test calendário', () => {
    
    it('cenario1', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signupadmin/"]').click()
        cy.wait(1500)
        cy.get('#username').type("administrador")
        cy.wait(1500)
        cy.get('#email').type("adm@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("administrador")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(7) > a').click()
        cy.wait(1500)
        cy.get('#name').type("Projetinho")
        cy.wait(1500)
        cy.get('#description').type("Descriçãozinha")
        cy.wait(1500)
        cy.get('#participants').type("UserA,UserB")
        cy.wait(1500)
        cy.get('#start_date').type("2024-06-29")
        cy.wait(1500)
        cy.get('#end_date').type("2024-07-04")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get(':nth-child(1) > a').click()
        cy.wait(1500)
    })
    it('cenario2', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signupadmin/"]').click()
        cy.wait(1500)
        cy.get('#username').type("administrador")
        cy.wait(1500)
        cy.get('#email').type("adm@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("administrador")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(7) > a').click()
        cy.wait(1500)
        cy.get('#name').type("Projeto EYE")
        cy.wait(1500)
        cy.get('#description').type("Executar todas as funções do projeto EYE")
        cy.wait(1500)
        cy.get('#participants').type("UserA,UserB")
        cy.wait(1500)
        cy.get('#start_date').type("2024-06-29")
        cy.wait(1500)
        cy.get('#end_date').type("2024-07-04")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get(':nth-child(3) > a').click()
        cy.wait(1500)
        cy.get('#nome').type("UserA")
        cy.wait(1500)
        cy.get('#email').type("A@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("UserA")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
    })
    it('cenario3', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get('[href="/signupadmin/"]').click()
        cy.wait(1500)
        cy.get('#username').type("administrador")
        cy.wait(1500)
        cy.get('#email').type("adm@gmail.com")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get('#nome').type("administrador")
        cy.wait(1500)
        cy.get('[type="password"]').type("12345")
        cy.wait(1500)
        cy.get('.submitbtn').click()
        cy.wait(1500)
        cy.get(':nth-child(7) > a').click()
        cy.wait(1500)
        cy.get('#name').type("ProjetoA")
        cy.wait(1500)
        cy.get('#description').type("DescriçãoA")
        cy.wait(1500)
        cy.get('#participants').type("UserA,UserB")
        cy.wait(1500)
        cy.get('#start_date').type("2024-04-29")
        cy.wait(1500)
        cy.get('#end_date').type("2024-05-04")
        cy.wait(1500)
        cy.get('.btn').click()
        cy.wait(1500)
        cy.get(':nth-child(1) > a').click()
        cy.wait(1500)
        cy.get('#expirados-tab').click()
        cy.wait(1500)
    })

})