# Generated by Django 4.2.8 on 2024-04-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_real'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Real',
            new_name='Projeto',
        ),
    ]
