# Generated by Django 4.2.8 on 2024-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_real_projeto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
