# Generated by Django 4.2.8 on 2024-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_project_alter_projeto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('arq', models.FileField(upload_to='img')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.TextField(default='defalt'),
            preserve_default=False,
        ),
    ]
