# Generated by Django 5.0.4 on 2024-04-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_person_delete_myfile_alter_projeto_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonUser',
        ),
    ]
