# Generated by Django 5.0.4 on 2024-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_personuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='arq',
            field=models.URLField(),
        ),
    ]
