# Generated by Django 5.0.4 on 2024-05-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_avaliacao_usuario_alter_avaliacao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
    ]
