# Generated by Django 5.0.4 on 2024-05-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_avaliacao2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao2',
        ),
    ]
