# Generated by Django 5.0.4 on 2024-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='descricao',
            field=models.TextField(),
        ),
    ]
