# Generated by Django 5.0.4 on 2024-05-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_avaliacao3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
