# Generated by Django 5.0.4 on 2024-05-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_descricao_usuario_foto_usuario'),
        ('home', '0020_delete_avaliacao'),
    ]

    operations = [
    ]
