# Generated by Django 5.0.4 on 2024-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_anotações'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotações',
            name='titulo',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
