# Generated by Django 5.0.4 on 2024-05-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_anotações_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participants',
            field=models.CharField(max_length=255),
        ),
    ]
